baseURL = "https://muqawlat.github.io/kuwait-contracting/"
languageCode = "ar"
title = "أفضل شركة مقاولات في الكويت | أبو كاراس"

[params]
  company_name = "مقاولات أبو كاراس"
  phone = "+965 50333141"
  address = "مدينة الكويت"
  # قائمة الخدمات (للتحكم بها من هنا)
  services = [
    "جميع اعمال الصحى والكهرباء",
    "تركيب جبس بورد",
    "اعمال صبغ",
    "تمديد حمامات ومطابخ",
    "تكسير"
  ]
  tagline = "تنفيذ مشاريع المقاولات بجودة وموثوقية في الكويت"
